package com.gq.meter.xchange.object;

// Generated May 2, 2013 12:01:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ClientData generated by hbm2java
 */
public class ClientData implements java.io.Serializable {

    private Long runId;
    private String meterId;
    private String data;
    private Date creDttm;
    private String comment;

    public ClientData() {
    }

    public ClientData(String meterId, String data, Date creDttm) {
        this.meterId = meterId;
        this.data = data;
        this.creDttm = creDttm;
    }

    public ClientData(Long runId, String meterId, String data, Date creDttm, String comment) {
        this.runId = runId;
        this.meterId = meterId;
        this.data = data;
        this.creDttm = creDttm;
        this.comment = comment;
    }

    public Long getRunId() {
        return runId;
    }

    public void setRunId(Long runId) {
        this.runId = runId;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

}
