package com.gq.meter.xchange.object;

// Generated Mar 1, 2013 12:56:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EnterpriseMeter generated by hbm2java
 */
public class EnterpriseMeter implements java.io.Serializable {

    private String meterId;
    private String protocolId;
    private String enterpriseId;
    private String descr;
    private String address;
    private String phone;
    private char storeFwd;
    private String fwdUrl;
    private Date creDttm;

    public EnterpriseMeter() {
    }

    public EnterpriseMeter(String meterId, String protocolId, String enterpriseId, String descr, char storeFwd,
            Date creDttm) {
        this.meterId = meterId;
        this.protocolId = protocolId;
        this.enterpriseId = enterpriseId;
        this.descr = descr;
        this.storeFwd = storeFwd;
        this.creDttm = creDttm;
    }

    public EnterpriseMeter(String meterId, String protocolId, String enterpriseId, String descr, String address,
            String phone, char storeFwd, String fwdUrl, Date creDttm) {
        this.meterId = meterId;
        this.protocolId = protocolId;
        this.enterpriseId = enterpriseId;
        this.descr = descr;
        this.address = address;
        this.phone = phone;
        this.storeFwd = storeFwd;
        this.fwdUrl = fwdUrl;
        this.creDttm = creDttm;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getEnterpriseId() {
        return this.enterpriseId;
    }

    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public char getStoreFwd() {
        return this.storeFwd;
    }

    public void setStoreFwd(char storeFwd) {
        this.storeFwd = storeFwd;
    }

    public String getFwdUrl() {
        return this.fwdUrl;
    }

    public void setFwdUrl(String fwdUrl) {
        this.fwdUrl = fwdUrl;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

}
