package com.gq.meter.xchange.object;

// Generated Mar 1, 2013 12:57:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GateKeeperAudit generated by hbm2java
 */
public class GateKeeperAudit implements java.io.Serializable {

    private String meterId;
    private String comment;
    private Long scnAlwd;
    private Date expDttm;
    private Date creDttm;

    public GateKeeperAudit() {
    }

    public GateKeeperAudit(String meterId, String comment, Date creDttm) {
        this.meterId = meterId;
        this.comment = comment;
        this.creDttm = creDttm;
    }

    public GateKeeperAudit(String meterId, String comment, Long scnAlwd, Date expDttm, Date creDttm) {
        this.meterId = meterId;
        this.comment = comment;
        this.scnAlwd = scnAlwd;
        this.expDttm = expDttm;
        this.creDttm = creDttm;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Long getScnAlwd() {
        return this.scnAlwd;
    }

    public void setScnAlwd(Long scnAlwd) {
        this.scnAlwd = scnAlwd;
    }

    public Date getExpDttm() {
        return this.expDttm;
    }

    public void setExpDttm(Date expDttm) {
        this.expDttm = expDttm;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

}
