package com.gq.meter.xchange.object;
// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Goal generated by hbm2java
 */
public class Goal implements java.io.Serializable {

    private String goalId;
    private String descr;
    private String perfNotes;
    private char timeBound;
    private byte[] img;
    private GoalInput goalInput;
    private Set goalSnpshts = new HashSet(0);

    public Goal() {
    }

    public Goal(String goalId, String descr, char timeBound) {
        this.goalId = goalId;
        this.descr = descr;
        this.timeBound = timeBound;
    }

    public Goal(String goalId, String descr, String perfNotes, char timeBound, byte[] img, GoalInput goalInput,
            Set goalSnpshts) {
        this.goalId = goalId;
        this.descr = descr;
        this.perfNotes = perfNotes;
        this.timeBound = timeBound;
        this.img = img;
        this.goalInput = goalInput;
        this.goalSnpshts = goalSnpshts;
    }

    public String getGoalId() {
        return this.goalId;
    }

    public void setGoalId(String goalId) {
        this.goalId = goalId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getPerfNotes() {
        return this.perfNotes;
    }

    public void setPerfNotes(String perfNotes) {
        this.perfNotes = perfNotes;
    }

    public char getTimeBound() {
        return this.timeBound;
    }

    public void setTimeBound(char timeBound) {
        this.timeBound = timeBound;
    }

    public byte[] getImg() {
        return this.img;
    }

    public void setImg(byte[] img) {
        this.img = img;
    }

    public GoalInput getGoalInput() {
        return this.goalInput;
    }

    public void setGoalInput(GoalInput goalInput) {
        this.goalInput = goalInput;
    }

    public Set getGoalSnpshts() {
        return this.goalSnpshts;
    }

    public void setGoalSnpshts(Set goalSnpshts) {
        this.goalSnpshts = goalSnpshts;
    }

}
