package com.gq.meter.xchange.object;

// default package
// Generated Sep 13, 2013 10:43:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * GoalInputId generated by hbm2java
 */
public class GoalInputId implements java.io.Serializable {

    private String goalId;
    private short inputId;

    public GoalInputId() {
    }

    public GoalInputId(String goalId, short inputId) {
        this.goalId = goalId;
        this.inputId = inputId;
    }

    public String getGoalId() {
        return this.goalId;
    }

    public void setGoalId(String goalId) {
        this.goalId = goalId;
    }

    public short getInputId() {
        return this.inputId;
    }

    public void setInputId(short inputId) {
        this.inputId = inputId;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof GoalInputId)) return false;
        GoalInputId castOther = (GoalInputId) other;

        return ((this.getGoalId() == castOther.getGoalId()) || (this.getGoalId() != null
                && castOther.getGoalId() != null && this.getGoalId().equals(castOther.getGoalId())))
                && (this.getInputId() == castOther.getInputId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getGoalId() == null ? 0 : this.getGoalId().hashCode());
        result = 37 * result + this.getInputId();
        return result;
    }

}
