package com.gq.meter.xchange.object;
// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

/**
 * PwrSrc generated by hbm2java
 */
public class PwrSrc implements java.io.Serializable {

    private String id;
    private String src;

    public PwrSrc() {
    }

    public PwrSrc(String id) {
        this.id = id;
    }

    public PwrSrc(String id, String src) {
        this.id = id;
        this.src = src;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSrc() {
        return this.src;
    }

    public void setSrc(String src) {
        this.src = src;
    }

}
