package com.gq.meter.xchange.object;

// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TaskAsst generated by hbm2java
 */
public class TaskAsst implements java.io.Serializable {

    private byte tsId;
    private ChartType chartType;
    private String descr;
    private String tsql;
    private Character dynamic;
    private String colHdr;
    private char relatdDb;
    private String posId;
    private Set taskTmplts = new HashSet(0);

    public TaskAsst() {
    }

    public TaskAsst(byte tsId, String descr, String tsql, char relatdDb) {
        this.tsId = tsId;
        this.descr = descr;
        this.tsql = tsql;
        this.relatdDb = relatdDb;
    }

    public TaskAsst(byte tsId, ChartType chartType, String descr, String tsql, Character dynamic, String colHdr,
            char relatdDb, String posId, Set taskTmplts) {
        this.tsId = tsId;
        this.chartType = chartType;
        this.descr = descr;
        this.tsql = tsql;
        this.dynamic = dynamic;
        this.colHdr = colHdr;
        this.relatdDb = relatdDb;
        this.posId = posId;
        this.taskTmplts = taskTmplts;
    }

    public byte getTsId() {
        return this.tsId;
    }

    public void setTsId(byte tsId) {
        this.tsId = tsId;
    }

    public ChartType getChartType() {
        return this.chartType;
    }

    public void setChartType(ChartType chartType) {
        this.chartType = chartType;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getTsql() {
        return this.tsql;
    }

    public void setTsql(String tsql) {
        this.tsql = tsql;
    }

    public Character getDynamic() {
        return this.dynamic;
    }

    public void setDynamic(Character dynamic) {
        this.dynamic = dynamic;
    }

    public String getColHdr() {
        return this.colHdr;
    }

    public void setColHdr(String colHdr) {
        this.colHdr = colHdr;
    }

    public char getRelatdDb() {
        return this.relatdDb;
    }

    public void setRelatdDb(char relatdDb) {
        this.relatdDb = relatdDb;
    }

    public String getPosId() {
        return posId;
    }

    public void setPosId(String posId) {
        this.posId = posId;
    }

    public Set getTaskTmplts() {
        return this.taskTmplts;
    }

    public void setTaskTmplts(Set taskTmplts) {
        this.taskTmplts = taskTmplts;
    }

}
