package com.gq.meter.xchange.object;

// default package
// Generated Sep 24, 2013 3:26:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * TaskTmpltId generated by hbm2java
 */
public class TaskTmpltId implements java.io.Serializable {

    private byte taskId;
    private String goalId;

    public TaskTmpltId() {
    }

    public TaskTmpltId(byte taskId, String goalId) {
        this.taskId = taskId;
        this.goalId = goalId;
    }

    public byte getTaskId() {
        return this.taskId;
    }

    public void setTaskId(byte taskId) {
        this.taskId = taskId;
    }

    public String getGoalId() {
        return this.goalId;
    }

    public void setGoalId(String goalId) {
        this.goalId = goalId;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TaskTmpltId)) return false;
        TaskTmpltId castOther = (TaskTmpltId) other;

        return (this.getTaskId() == castOther.getTaskId())
                && ((this.getGoalId() == castOther.getGoalId()) || (this.getGoalId() != null
                        && castOther.getGoalId() != null && this.getGoalId().equals(castOther.getGoalId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTaskId();
        result = 37 * result + (getGoalId() == null ? 0 : this.getGoalId().hashCode());
        return result;
    }

}
