package com.gq.meter.object;

// default package
// Generated Jul 26, 2013 4:15:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AssetImp generated by hbm2java
 */
public class AssetImp implements java.io.Serializable {

    private int impLvl;
    private String descr;
    private Set assets = new HashSet(0);

    public AssetImp() {
    }

    public AssetImp(int impLvl, String descr) {
        this.impLvl = impLvl;
        this.descr = descr;
    }

    public AssetImp(int impLvl, String descr, Set assets) {
        this.impLvl = impLvl;
        this.descr = descr;
        this.assets = assets;
    }

    public int getImpLvl() {
        return impLvl;
    }

    public void setImpLvl(int impLvl) {
        this.impLvl = impLvl;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Set getAssets() {
        return this.assets;
    }

    public void setAssets(Set assets) {
        this.assets = assets;
    }

}
