package com.gq.meter.object;

// default package
// Generated Jul 26, 2013 4:15:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Asset generated by hbm2java
 */
public class Asset implements java.io.Serializable {

    private String assetId;
    private DevCtlg devCtlg;
    private AssetImp assetImp;
    private String protocolId;
    private String name;
    private String descr;
    private String contact;
    private String location;
    private int srvrAppId;
    private String assetUsg;
    private String ownership;
    private String dcEnt;
    private Character active;
    private Date inactiveDttm;
    private String ctlgId;
    private int imp_level;

    public Asset() {
    }

    public Asset(String assetId, String protocolId, String assetUsg) {
        this.assetId = assetId;
        this.protocolId = protocolId;
        this.assetUsg = assetUsg;
    }

    public Asset(String assetId, DevCtlg devCtlg, AssetImp assetImp, String protocolId, String name, String descr,
            String contact, String location, int srvrAppId, String assetUsg, String ownership, String dcEnt,
            Character active, Date inactiveDttm) {
        this.assetId = assetId;
        this.devCtlg = devCtlg;
        this.assetImp = assetImp;
        this.protocolId = protocolId;
        this.name = name;
        this.descr = descr;
        this.contact = contact;
        this.location = location;
        this.srvrAppId = srvrAppId;
        this.assetUsg = assetUsg;
        this.ownership = ownership;
        this.dcEnt = dcEnt;
        this.active = active;
        this.inactiveDttm = inactiveDttm;
    }

    public Asset(String assetId, String protocolId, String name, String descr, String contact, String location,
            int srvrAppId, String assetUsg, String ctlgId, int imp_level) {
        super();
        this.assetId = assetId;
        this.protocolId = protocolId;
        this.name = name;
        this.descr = descr;
        this.contact = contact;
        this.location = location;
        this.srvrAppId = srvrAppId;
        this.assetUsg = assetUsg;
        this.ctlgId = ctlgId;
        this.imp_level = imp_level;
    }

    public String getCtlgId() {
        return ctlgId;
    }

    public void setCtlgId(String ctlgId) {
        this.ctlgId = ctlgId;
    }

    public int getImp_level() {
        return imp_level;
    }

    public void setImp_level(int imp_level) {
        this.imp_level = imp_level;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public DevCtlg getDevCtlg() {
        return this.devCtlg;
    }

    public void setDevCtlg(DevCtlg devCtlg) {
        this.devCtlg = devCtlg;
    }

    public AssetImp getAssetImp() {
        return this.assetImp;
    }

    public void setAssetImp(AssetImp assetImp) {
        this.assetImp = assetImp;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public int getSrvrAppId() {
        return srvrAppId;
    }

    public void setSrvrAppId(int srvrAppId) {
        this.srvrAppId = srvrAppId;
    }

    public String getAssetUsg() {
        return this.assetUsg;
    }

    public void setAssetUsg(String assetUsg) {
        this.assetUsg = assetUsg;
    }

    public String getOwnership() {
        return this.ownership;
    }

    public void setOwnership(String ownership) {
        this.ownership = ownership;
    }

    public String getDcEnt() {
        return this.dcEnt;
    }

    public void setDcEnt(String dcEnt) {
        this.dcEnt = dcEnt;
    }

    public Character getActive() {
        return this.active;
    }

    public void setActive(Character active) {
        this.active = active;
    }

    public Date getInactiveDttm() {
        return this.inactiveDttm;
    }

    public void setInactiveDttm(Date inactiveDttm) {
        this.inactiveDttm = inactiveDttm;
    }

}
