package com.gq.meter.object;

// default package
// Generated Mar 4, 2013 2:18:48 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssetErr generated by hbm2java
 */
public class AssetErr implements java.io.Serializable {

    private long sid;
    private int runId;
    private String sysDesc;
    private String errMsg;

    public AssetErr() {
    }

    public AssetErr(int runId, String sysDesc, String errMsg) {
        this.runId = runId;
        this.sysDesc = sysDesc;
        this.errMsg = errMsg;
    }

    public long getSid() {
        return this.sid;
    }

    public void setSid(long sid) {
        this.sid = sid;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getSysDesc() {
        return this.sysDesc;
    }

    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc;
    }

    public String getErrMsg() {
        return this.errMsg;
    }

    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

}
