package com.gq.meter.object;

/**
 * CompConnDeviceId generated by hbm2java
 */
public class CompConnDeviceId implements java.io.Serializable {

    private int runId;
    private String assetId;
    private String ipAddr;
    private Integer port;

    public CompConnDeviceId() {
    }

    public CompConnDeviceId(int runId, String assetId, String ipAddr) {
        this.runId = runId;
        this.assetId = assetId;
        this.ipAddr = ipAddr;
    }

    public CompConnDeviceId(int runId, String assetId, String ipAddr, Integer port) {
        this.runId = runId;
        this.assetId = assetId;
        this.ipAddr = ipAddr;
        this.port = port;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public String getIpAddr() {
        return this.ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    public Integer getPort() {
        return this.port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CompConnDeviceId)) return false;
        CompConnDeviceId castOther = (CompConnDeviceId) other;

        return (this.getRunId() == castOther.getRunId())
                && ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
                        && castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())))
                && ((this.getIpAddr() == castOther.getIpAddr()) || (this.getIpAddr() != null
                        && castOther.getIpAddr() != null && this.getIpAddr().equals(castOther.getIpAddr())))
                && ((this.getPort() == castOther.getPort()) || (this.getPort() != null && castOther.getPort() != null && this
                        .getPort().equals(castOther.getPort())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRunId();
        result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
        result = 37 * result + (getIpAddr() == null ? 0 : this.getIpAddr().hashCode());
        result = 37 * result + (getPort() == null ? 0 : this.getPort().hashCode());
        return result;
    }

}
