package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 12:58:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CompInstSoftwareId generated by hbm2java
 */
public class CompInstSoftwareId implements java.io.Serializable {

    private int runId;
    private String assetId;
    private String name;
    private Date instDttm;

    public CompInstSoftwareId() {
    }

    public CompInstSoftwareId(int runId, String assetId, String name, Date instDttm) {
        this.runId = runId;
        this.assetId = assetId;
        this.name = name;
        this.instDttm = instDttm;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getInstDttm() {
        return this.instDttm;
    }

    public void setInstDttm(Date instDttm) {
        this.instDttm = instDttm;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CompInstSoftwareId)) return false;
        CompInstSoftwareId castOther = (CompInstSoftwareId) other;

        return (this.getRunId() == castOther.getRunId())
                && ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
                        && castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())))
                && ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
                        .getName().equals(castOther.getName())))
                && ((this.getInstDttm() == castOther.getInstDttm()) || (this.getInstDttm() != null
                        && castOther.getInstDttm() != null && this.getInstDttm().equals(castOther.getInstDttm())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRunId();
        result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getInstDttm() == null ? 0 : this.getInstDttm().hashCode());
        return result;
    }

}
