package com.gq.meter.object;

// default package
// Generated Jul 26, 2013 4:15:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DevCtlg generated by hbm2java
 */
public class DevCtlg implements java.io.Serializable {

    private String ctlgId;
    private String protocolId;
    private String descr;
    private short idleThreshold;
    private short loadThreshold;
    private double idleWatt;
    private double loadWatt;
    private Double enPerMinLoad;
    private Double enPerMinIdle;
    private Double servrCost;
    private Integer noOfCore;
    private Double cpu;
    private Integer ram;
    private Integer diskGb;
    private Integer monthlyRent;
    private String compType;
    private Set assets = new HashSet(0);

    public DevCtlg() {
    }

    public DevCtlg(String ctlgId, String protocolId, String descr, short idleThreshold, short loadThreshold,
            double idleWatt, double loadWatt) {
        this.ctlgId = ctlgId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.idleThreshold = idleThreshold;
        this.loadThreshold = loadThreshold;
        this.idleWatt = idleWatt;
        this.loadWatt = loadWatt;
    }

    public DevCtlg(String ctlgId, String protocolId, String descr, short idleThreshold, short loadThreshold,
            double idleWatt, double loadWatt, Double enPerMinLoad, Double enPerMinIdle, Double servrCost,
            Integer noOfCore, Double cpu, Integer ram, Integer diskGb, Integer monthlyRent, String compType, Set assets) {
        this.ctlgId = ctlgId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.idleThreshold = idleThreshold;
        this.loadThreshold = loadThreshold;
        this.idleWatt = idleWatt;
        this.loadWatt = loadWatt;
        this.enPerMinLoad = enPerMinLoad;
        this.enPerMinIdle = enPerMinIdle;
        this.servrCost = servrCost;
        this.noOfCore = noOfCore;
        this.cpu = cpu;
        this.ram = ram;
        this.diskGb = diskGb;
        this.monthlyRent = monthlyRent;
        this.compType = compType;
        this.assets = assets;
    }

    public String getCtlgId() {
        return this.ctlgId;
    }

    public void setCtlgId(String ctlgId) {
        this.ctlgId = ctlgId;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public short getIdleThreshold() {
        return this.idleThreshold;
    }

    public void setIdleThreshold(short idleThreshold) {
        this.idleThreshold = idleThreshold;
    }

    public short getLoadThreshold() {
        return this.loadThreshold;
    }

    public void setLoadThreshold(short loadThreshold) {
        this.loadThreshold = loadThreshold;
    }

    public double getIdleWatt() {
        return this.idleWatt;
    }

    public void setIdleWatt(double idleWatt) {
        this.idleWatt = idleWatt;
    }

    public double getLoadWatt() {
        return this.loadWatt;
    }

    public void setLoadWatt(double loadWatt) {
        this.loadWatt = loadWatt;
    }

    public Double getEnPerMinLoad() {
        return this.enPerMinLoad;
    }

    public void setEnPerMinLoad(Double enPerMinLoad) {
        this.enPerMinLoad = enPerMinLoad;
    }

    public Double getEnPerMinIdle() {
        return this.enPerMinIdle;
    }

    public void setEnPerMinIdle(Double enPerMinIdle) {
        this.enPerMinIdle = enPerMinIdle;
    }

    public Double getServrCost() {
        return this.servrCost;
    }

    public void setServrCost(Double servrCost) {
        this.servrCost = servrCost;
    }

    public Integer getNoOfCore() {
        return this.noOfCore;
    }

    public void setNoOfCore(Integer noOfCore) {
        this.noOfCore = noOfCore;
    }

    public Double getCpu() {
        return this.cpu;
    }

    public void setCpu(Double cpu) {
        this.cpu = cpu;
    }

    public Integer getRam() {
        return this.ram;
    }

    public void setRam(Integer ram) {
        this.ram = ram;
    }

    public Integer getDiskGb() {
        return this.diskGb;
    }

    public void setDiskGb(Integer diskGb) {
        this.diskGb = diskGb;
    }

    public Integer getMonthlyRent() {
        return this.monthlyRent;
    }

    public void setMonthlyRent(Integer monthlyRent) {
        this.monthlyRent = monthlyRent;
    }

    public String getCompType() {
        return this.compType;
    }

    public void setCompType(String compType) {
        this.compType = compType;
    }

    public Set getAssets() {
        return this.assets;
    }

    public void setAssets(Set assets) {
        this.assets = assets;
    }

}
