package com.gq.meter.object;

// default package
// Generated Jul 10, 2013 1:41:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Enterprise generated by hbm2java
 */
public class Enterprise implements java.io.Serializable {

    private String enterpriseId;
    private String EName;
    private String phone;
    private String email;
    private String userId;
    private Date creDttm;
    private String empRange;
    private Integer entSqft;
    private Integer entAssetCnt;
    private Integer dcSqft;
    private Integer dcAssetCnt;
    private Integer dcUsePctg;
    private Integer dcTemp;
    private String comments;

    public Enterprise() {
    }

    public Enterprise(String enterpriseId, String EName, String phone, String email, String userId, Date creDttm) {
        this.enterpriseId = enterpriseId;
        this.EName = EName;
        this.phone = phone;
        this.email = email;
        this.userId = userId;
        this.creDttm = creDttm;
    }

    public Enterprise(String enterpriseId, String EName, String phone, String email, String userId, Date creDttm,
            String empRange, Integer entSqft, Integer entAssetCnt, Integer dcSqft, Integer dcAssetCnt,
            Integer dcUsePctg, Integer dcTemp, String comments) {
        this.enterpriseId = enterpriseId;
        this.EName = EName;
        this.phone = phone;
        this.email = email;
        this.userId = userId;
        this.creDttm = creDttm;
        this.empRange = empRange;
        this.entSqft = entSqft;
        this.entAssetCnt = entAssetCnt;
        this.dcSqft = dcSqft;
        this.dcAssetCnt = dcAssetCnt;
        this.dcUsePctg = dcUsePctg;
        this.dcTemp = dcTemp;
        this.comments = comments;
    }

    public String getEnterpriseId() {
        return this.enterpriseId;
    }

    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public String getEName() {
        return this.EName;
    }

    public void setEName(String EName) {
        this.EName = EName;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

    public String getEmpRange() {
        return this.empRange;
    }

    public void setEmpRange(String empRange) {
        this.empRange = empRange;
    }

    public Integer getEntSqft() {
        return this.entSqft;
    }

    public void setEntSqft(Integer entSqft) {
        this.entSqft = entSqft;
    }

    public Integer getEntAssetCnt() {
        return this.entAssetCnt;
    }

    public void setEntAssetCnt(Integer entAssetCnt) {
        this.entAssetCnt = entAssetCnt;
    }

    public Integer getDcSqft() {
        return this.dcSqft;
    }

    public void setDcSqft(Integer dcSqft) {
        this.dcSqft = dcSqft;
    }

    public Integer getDcAssetCnt() {
        return this.dcAssetCnt;
    }

    public void setDcAssetCnt(Integer dcAssetCnt) {
        this.dcAssetCnt = dcAssetCnt;
    }

    public Integer getDcUsePctg() {
        return this.dcUsePctg;
    }

    public void setDcUsePctg(Integer dcUsePctg) {
        this.dcUsePctg = dcUsePctg;
    }

    public Integer getDcTemp() {
        return this.dcTemp;
    }

    public void setDcTemp(Integer dcTemp) {
        this.dcTemp = dcTemp;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
