package com.gq.meter.object;

// Generated Feb 18, 2013 3:31:15 PM by Hibernate Tools 3.4.0.CR1

/**
 * LocationMaster generated by hbm2java
 */
public class LocationMaster implements java.io.Serializable {

    private String locId;
    private String locName;
    private Double lossVar;
    private Double lat;
    private Double lng;
    private double sumrPue;
    private double wntrPue;

    public LocationMaster() {
    }

    public LocationMaster(String locId, String locName, double sumrPue, double wntrPue) {
        this.locId = locId;
        this.locName = locName;
        this.sumrPue = sumrPue;
        this.wntrPue = wntrPue;
    }

    public LocationMaster(String locId, String locName, Double lossVar, Double lat, Double lng, double sumrPue,
            double wntrPue) {
        super();
        this.locId = locId;
        this.locName = locName;
        this.lossVar = lossVar;
        this.lat = lat;
        this.lng = lng;
        this.sumrPue = sumrPue;
        this.wntrPue = wntrPue;
    }

    public String getLocId() {
        return this.locId;
    }

    public void setLocId(String locId) {
        this.locId = locId;
    }

    public String getLocName() {
        return this.locName;
    }

    public void setLocName(String locName) {
        this.locName = locName;
    }

    public Double getLossVar() {
        return this.lossVar;
    }

    public void setLossVar(Double lossVar) {
        this.lossVar = lossVar;
    }

    public Double getLat() {
        return this.lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLng() {
        return this.lng;
    }

    public void setLng(Double lng) {
        this.lng = lng;
    }

    public double getSumrPue() {
        return this.sumrPue;
    }

    public void setSumrPue(double sumrPue) {
        this.sumrPue = sumrPue;
    }

    public double getWntrPue() {
        return this.wntrPue;
    }

    public void setWntrPue(double wntrPue) {
        this.wntrPue = wntrPue;
    }

}
