package com.gq.meter.object;

// Generated Feb 18, 2013 3:27:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * OsType generated by hbm2java
 */
public class OsType implements java.io.Serializable {

    private String osId;
    private String descr;

    public OsType() {
    }

    public OsType(String osId, String descr) {
        super();
        this.osId = osId;
        this.descr = descr;
    }

    public String getOsId() {
        return this.osId;
    }

    public void setOsId(String osId) {
        this.osId = osId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
