package com.gq.meter.object;

// default package
// Generated Apr 10, 2013 12:25:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rcmndtn generated by hbm2java
 */
public class Rcmndtn implements java.io.Serializable {

    private byte rcmndtnId;
    private String rcmndtn;
    private String extrnlInflnce;
    private Byte hrdshp;
    private String timeRealztn;
    private String notes;

    public Rcmndtn() {
    }

    public Rcmndtn(byte rcmndtnId, String rcmndtn) {
        this.rcmndtnId = rcmndtnId;
        this.rcmndtn = rcmndtn;
    }

    public Rcmndtn(byte rcmndtnId, String rcmndtn, String extrnlInflnce, Byte hrdshp, String timeRealztn, String notes) {
        this.rcmndtnId = rcmndtnId;
        this.rcmndtn = rcmndtn;
        this.extrnlInflnce = extrnlInflnce;
        this.hrdshp = hrdshp;
        this.timeRealztn = timeRealztn;
        this.notes = notes;
    }

    public byte getRcmndtnId() {
        return this.rcmndtnId;
    }

    public void setRcmndtnId(byte rcmndtnId) {
        this.rcmndtnId = rcmndtnId;
    }

    public String getRcmndtn() {
        return this.rcmndtn;
    }

    public void setRcmndtn(String rcmndtn) {
        this.rcmndtn = rcmndtn;
    }

    public String getExtrnlInflnce() {
        return this.extrnlInflnce;
    }

    public void setExtrnlInflnce(String extrnlInflnce) {
        this.extrnlInflnce = extrnlInflnce;
    }

    public Byte getHrdshp() {
        return this.hrdshp;
    }

    public void setHrdshp(Byte hrdshp) {
        this.hrdshp = hrdshp;
    }

    public String getTimeRealztn() {
        return this.timeRealztn;
    }

    public void setTimeRealztn(String timeRealztn) {
        this.timeRealztn = timeRealztn;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

}
