package com.gq.meter.object;

// default package
// Generated Apr 10, 2013 12:25:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RcmndtnInst generated by hbm2java
 */
public class RcmndtnInst implements java.io.Serializable {

    private byte snpshtId;
    private Date startDate;
    private Date finishDate;
    private Integer dcOpBfr;
    private Integer dcOpAft;

    public RcmndtnInst() {
    }

    public RcmndtnInst(byte snpshtId, Date startDate) {
        this.snpshtId = snpshtId;
        this.startDate = startDate;
    }

    public RcmndtnInst(byte snpshtId, Date startDate, Date finishDate, Integer dcOpBfr, Integer dcOpAft) {
        this.snpshtId = snpshtId;
        this.startDate = startDate;
        this.finishDate = finishDate;
        this.dcOpBfr = dcOpBfr;
        this.dcOpAft = dcOpAft;
    }

    public byte getSnpshtId() {
        return this.snpshtId;
    }

    public void setSnpshtId(byte snpshtId) {
        this.snpshtId = snpshtId;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getFinishDate() {
        return this.finishDate;
    }

    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    public Integer getDcOpBfr() {
        return this.dcOpBfr;
    }

    public void setDcOpBfr(Integer dcOpBfr) {
        this.dcOpBfr = dcOpBfr;
    }

    public Integer getDcOpAft() {
        return this.dcOpAft;
    }

    public void setDcOpAft(Integer dcOpAft) {
        this.dcOpAft = dcOpAft;
    }

}
