package com.gq.meter.object;
// default package
// Generated Dec 30, 2013 4:14:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpeedTestSnpshtId generated by hbm2java
 */
public class SpeedTestSnpshtId implements java.io.Serializable {

	private String assetId;
	private long runId;

	public SpeedTestSnpshtId() {
	}

	public SpeedTestSnpshtId(String assetId, long runId) {
		this.assetId = assetId;
		this.runId = runId;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public long getRunId() {
		return this.runId;
	}

	public void setRunId(long runId) {
		this.runId = runId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpeedTestSnpshtId))
			return false;
		SpeedTestSnpshtId castOther = (SpeedTestSnpshtId) other;

		return ((this.getAssetId() == castOther.getAssetId()) || (this
				.getAssetId() != null && castOther.getAssetId() != null && this
				.getAssetId().equals(castOther.getAssetId())))
				&& (this.getRunId() == castOther.getRunId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result + (int) this.getRunId();
		return result;
	}

}
