package com.gq.meter.xchange.object;
// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DataTypes generated by hbm2java
 */
public class DataTypes implements java.io.Serializable {

    private String dtvalue;
    private Set goalInputs = new HashSet(0);

    public DataTypes() {
    }

    public DataTypes(String dtvalue) {
        this.dtvalue = dtvalue;
    }

    public DataTypes(String dtvalue, Set goalInputs) {
        this.dtvalue = dtvalue;
        this.goalInputs = goalInputs;
    }

    public String getDtvalue() {
        return this.dtvalue;
    }

    public void setDtvalue(String dtvalue) {
        this.dtvalue = dtvalue;
    }

    public Set getGoalInputs() {
        return this.goalInputs;
    }

    public void setGoalInputs(Set goalInputs) {
        this.goalInputs = goalInputs;
    }

}
