package com.gq.meter.xchange.object;

//Generated May 2, 2013 12:10:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Enterprise generated by hbm2java
 */
public class Enterprise implements java.io.Serializable {

    private Short sid;
    private Character enterpriseId;
    private char blCd;
    private String EName;
    private String phone;
    private String email;
    private String userId;
    private String passwd;
    private Short secQtn1;
    private String ans1;
    private Short secQtn2;
    private String ans2;
    private Date creDttm;
    private char storeFwd;
    private String fwdUrl;
    private String fwdPwd;
    private Integer noOfEmpl;
    private Integer dcSqft;
    private Character regCmplt;
    private Double dcUsePctg;
    private Integer dcTemp;
    private String comments;

    public Enterprise() {
    }

    public Enterprise(Character enterpriseId, char blCd, String EName, String phone, String email, String userId,
            String passwd, Date creDttm, char storeFwd) {
        this.enterpriseId = enterpriseId;
        this.blCd = blCd;
        this.EName = EName;
        this.phone = phone;
        this.email = email;
        this.userId = userId;
        this.passwd = passwd;
        this.creDttm = creDttm;
        this.storeFwd = storeFwd;
    }

    public Enterprise(Character enterpriseId, char blCd, String EName, String phone, String email, String userId,
            String passwd, Short secQtn1, String ans1, Short secQtn2, String ans2, Date creDttm, char storeFwd,
            String fwdUrl, Integer noOfEmpl, Integer dcSqft, Character regCmplt, Double dcUsePctg, Integer dcTemp,
            String comments) {
        this.enterpriseId = enterpriseId;
        this.blCd = blCd;
        this.EName = EName;
        this.phone = phone;
        this.email = email;
        this.userId = userId;
        this.passwd = passwd;
        this.secQtn1 = secQtn1;
        this.ans1 = ans1;
        this.secQtn2 = secQtn2;
        this.ans2 = ans2;
        this.creDttm = creDttm;
        this.storeFwd = storeFwd;
        this.fwdUrl = fwdUrl;
        this.noOfEmpl = noOfEmpl;
        this.dcSqft = dcSqft;
        this.regCmplt = regCmplt;
        this.dcUsePctg = dcUsePctg;
        this.dcTemp = dcTemp;
        this.comments = comments;
    }

    public Short getSid() {
        return this.sid;
    }

    public void setSid(Short sid) {
        this.sid = sid;
    }

    public Character getEnterpriseId() {
        return this.enterpriseId;
    }

    public void setEnterpriseId(Character enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public char getBlCd() {
        return this.blCd;
    }

    public void setBlCd(char blCd) {
        this.blCd = blCd;
    }

    public String getEName() {
        return this.EName;
    }

    public void setEName(String EName) {
        this.EName = EName;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getPasswd() {
        return this.passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public Short getSecQtn1() {
        return this.secQtn1;
    }

    public void setSecQtn1(Short secQtn1) {
        this.secQtn1 = secQtn1;
    }

    public String getAns1() {
        return this.ans1;
    }

    public void setAns1(String ans1) {
        this.ans1 = ans1;
    }

    public Short getSecQtn2() {
        return this.secQtn2;
    }

    public void setSecQtn2(Short secQtn2) {
        this.secQtn2 = secQtn2;
    }

    public String getAns2() {
        return this.ans2;
    }

    public void setAns2(String ans2) {
        this.ans2 = ans2;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

    public char getStoreFwd() {
        return this.storeFwd;
    }

    public void setStoreFwd(char storeFwd) {
        this.storeFwd = storeFwd;
    }

    public String getFwdUrl() {
        return this.fwdUrl;
    }

    public void setFwdUrl(String fwdUrl) {
        this.fwdUrl = fwdUrl;
    }

    /**
     * @return the fwdPwd
     */
    public String getFwdPwd() {
        return fwdPwd;
    }

    /**
     * @param fwdPwd the fwdPwd to set
     */
    public void setFwdPwd(String fwdPwd) {
        this.fwdPwd = fwdPwd;
    }

    public Integer getNoOfEmpl() {
        return this.noOfEmpl;
    }

    public void setNoOfEmpl(Integer noOfEmpl) {
        this.noOfEmpl = noOfEmpl;
    }

    public Integer getDcSqft() {
        return this.dcSqft;
    }

    public void setDcSqft(Integer dcSqft) {
        this.dcSqft = dcSqft;
    }

    public Character getRegCmplt() {
        return this.regCmplt;
    }

    public void setRegCmplt(Character regCmplt) {
        this.regCmplt = regCmplt;
    }

    public Double getDcUsePctg() {
        return this.dcUsePctg;
    }

    public void setDcUsePctg(Double dcUsePctg) {
        this.dcUsePctg = dcUsePctg;
    }

    public Integer getDcTemp() {
        return this.dcTemp;
    }

    public void setDcTemp(Integer dcTemp) {
        this.dcTemp = dcTemp;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
