package com.gq.meter.xchange.object;
// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

/**
 * TaskChklstId generated by hbm2java
 */
public class TaskChklstId implements java.io.Serializable {

    private int snpshtId;
    private byte taskId;

    public TaskChklstId() {
    }

    public TaskChklstId(int snpshtId, byte taskId) {
        this.snpshtId = snpshtId;
        this.taskId = taskId;
    }

    public int getSnpshtId() {
        return this.snpshtId;
    }

    public void setSnpshtId(int snpshtId) {
        this.snpshtId = snpshtId;
    }

    public byte getTaskId() {
        return this.taskId;
    }

    public void setTaskId(byte taskId) {
        this.taskId = taskId;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TaskChklstId)) return false;
        TaskChklstId castOther = (TaskChklstId) other;

        return (this.getSnpshtId() == castOther.getSnpshtId()) && (this.getTaskId() == castOther.getTaskId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSnpshtId();
        result = 37 * result + this.getTaskId();
        return result;
    }

}
