package com.gq.meter.object;

// default package
// Generated Jul 10, 2013 1:41:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * AssetStrength generated by hbm2java
 */
public class AssetStrength implements java.io.Serializable {

    private byte impLvl;
    private String descr;

    public AssetStrength() {
    }

    public AssetStrength(byte impLvl, String descr) {
        this.impLvl = impLvl;
        this.descr = descr;
    }

    public byte getImpLvl() {
        return this.impLvl;
    }

    public void setImpLvl(byte impLvl) {
        this.impLvl = impLvl;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
