package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 2:44:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompConnDevice generated by hbm2java
 */
public class CompConnDevice implements java.io.Serializable {

    private CompConnDeviceId id;

    public CompConnDevice() {
    }

    public CompConnDevice(CompConnDeviceId id) {
        this.id = id;
    }

    public CompConnDeviceId getId() {
        return this.id;
    }

    public void setId(CompConnDeviceId id) {
        this.id = id;
    }

}
