package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 2:37:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompProcessId generated by hbm2java
 */
public class CompProcessId implements java.io.Serializable {

    private Long runId;
    private String assetId;
    private String procName;
    private int cpuShareCs;
    private int memShareKb;

    public CompProcessId() {
    }

    public CompProcessId(Long runId, String assetId, String procName, int cpuShareCs, int memShareKb) {
        this.runId = runId;
        this.assetId = assetId;
        this.procName = procName;
        this.cpuShareCs = cpuShareCs;
        this.memShareKb = memShareKb;
    }

    public Long getRunId() {
        return runId;
    }

    public void setRunId(Long runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public String getProcName() {
        return this.procName;
    }

    public void setProcName(String procName) {
        this.procName = procName;
    }

    public int getCpuShareCs() {
        return this.cpuShareCs;
    }

    public void setCpuShareCs(int cpuShareCs) {
        this.cpuShareCs = cpuShareCs;
    }

    public int getMemShareKb() {
        return this.memShareKb;
    }

    public void setMemShareKb(int memShareKb) {
        this.memShareKb = memShareKb;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((assetId == null) ? 0 : assetId.hashCode());
        result = prime * result + cpuShareCs;
        result = prime * result + memShareKb;
        result = prime * result + ((procName == null) ? 0 : procName.hashCode());
        result = prime * result + ((runId == null) ? 0 : runId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        CompProcessId other = (CompProcessId) obj;
        if (assetId == null) {
            if (other.assetId != null) {
                return false;
            }
        }
        else if (!assetId.equals(other.assetId)) {
            return false;
        }
        if (cpuShareCs != other.cpuShareCs) {
            return false;
        }
        if (memShareKb != other.memShareKb) {
            return false;
        }
        if (procName == null) {
            if (other.procName != null) {
                return false;
            }
        }
        else if (!procName.equals(other.procName)) {
            return false;
        }
        if (runId == null) {
            if (other.runId != null) {
                return false;
            }
        }
        else if (!runId.equals(other.runId)) {
            return false;
        }
        return true;
    }

}
