package com.gq.meter.object;

/**
 * CompConnDevice generated by hbm2java
 */
public class CompConnDevice implements java.io.Serializable {

    private CompConnDeviceId id;

    public CompConnDevice() {
    }

    public CompConnDevice(CompConnDeviceId id) {
        this.id = id;
    }

    public CompConnDeviceId getId() {
        return this.id;
    }

    public void setId(CompConnDeviceId id) {
        this.id = id;
    }

}
