package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 12:58:17 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompInstSoftware generated by hbm2java
 */
public class CompInstSoftware implements java.io.Serializable {

    private CompInstSoftwareId id;

    public CompInstSoftware() {
    }

    public CompInstSoftware(CompInstSoftwareId id) {
        this.id = id;
    }

    public CompInstSoftwareId getId() {
        return this.id;
    }

    public void setId(CompInstSoftwareId id) {
        this.id = id;
    }

}
