package com.gq.meter.object;
// default package
// Generated Feb 21, 2013 2:37:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompProcess generated by hbm2java
 */
public class CompProcess implements java.io.Serializable {

    private CompProcessId id;

    public CompProcess() {
    }

    public CompProcess(CompProcessId id) {
        this.id = id;
    }

    public CompProcessId getId() {
        return this.id;
    }

    public void setId(CompProcessId id) {
        this.id = id;
    }

}
