package com.gq.meter.object;
// default package
// Generated Feb 21, 2013 2:37:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompProcessId generated by hbm2java
 */
public class CompProcessId implements java.io.Serializable {

    private int runId;
    private String assetId;
    private String procName;
    private int cpuShareCs;
    private int memShareKb;

    public CompProcessId() {
    }

    public CompProcessId(int runId, String assetId, String procName, int cpuShareCs, int memShareKb) {
        this.runId = runId;
        this.assetId = assetId;
        this.procName = procName;
        this.cpuShareCs = cpuShareCs;
        this.memShareKb = memShareKb;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public String getProcName() {
        return this.procName;
    }

    public void setProcName(String procName) {
        this.procName = procName;
    }

    public int getCpuShareCs() {
        return this.cpuShareCs;
    }

    public void setCpuShareCs(int cpuShareCs) {
        this.cpuShareCs = cpuShareCs;
    }

    public int getMemShareKb() {
        return this.memShareKb;
    }

    public void setMemShareKb(int memShareKb) {
        this.memShareKb = memShareKb;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CompProcessId)) return false;
        CompProcessId castOther = (CompProcessId) other;

        return (this.getRunId() == castOther.getRunId())
                && ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
                        && castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())))
                && ((this.getProcName() == castOther.getProcName()) || (this.getProcName() != null
                        && castOther.getProcName() != null && this.getProcName().equals(castOther.getProcName())))
                && (this.getCpuShareCs() == castOther.getCpuShareCs())
                && (this.getMemShareKb() == castOther.getMemShareKb());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRunId();
        result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
        result = 37 * result + (getProcName() == null ? 0 : this.getProcName().hashCode());
        result = 37 * result + this.getCpuShareCs();
        result = 37 * result + this.getMemShareKb();
        return result;
    }

}
