package com.gq.meter.object;

// default package
// Generated Apr 10, 2013 12:24:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DscvryFile generated by hbm2java
 */
public class DscvryFile implements java.io.Serializable {

    private Byte sid;
    private String meterId;
    private String fileContent;
    private Date creDttm;

    public DscvryFile() {
    }

    public DscvryFile(String fileContent, Date creDttm) {
        this.fileContent = fileContent;
        this.creDttm = creDttm;
    }

    public DscvryFile(String meterId, String fileContent, Date creDttm) {
        this.meterId = meterId;
        this.fileContent = fileContent;
        this.creDttm = creDttm;
    }

    public Byte getSid() {
        return this.sid;
    }

    public void setSid(Byte sid) {
        this.sid = sid;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public String getFileContent() {
        return this.fileContent;
    }

    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

}
