package com.gq.meter.object;

// default package
// Generated Mar 6, 2013 12:33:25 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Meter generated by hbm2java
 */
public class Meter implements java.io.Serializable {

    private String meterId;
    private String protocolId;
    private String descr;
    private String address;
    private String phone;
    private char storeFwd;
    private String fwdUrl;
    private Date creDttm;

    public Meter() {
    }

    public Meter(String meterId, String protocolId, String descr, char storeFwd) {
        this.meterId = meterId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.storeFwd = storeFwd;
    }

    public Meter(String meterId, String protocolId, String descr, String address, String phone, char storeFwd,
            String fwdUrl, Date creDttm) {
        this.meterId = meterId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.address = address;
        this.phone = phone;
        this.storeFwd = storeFwd;
        this.fwdUrl = fwdUrl;
        this.creDttm = creDttm;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public char getStoreFwd() {
        return this.storeFwd;
    }

    public void setStoreFwd(char storeFwd) {
        this.storeFwd = storeFwd;
    }

    public String getFwdUrl() {
        return this.fwdUrl;
    }

    public void setFwdUrl(String fwdUrl) {
        this.fwdUrl = fwdUrl;
    }

    public Date getCreDttm() {
        return this.creDttm;
    }

    public void setCreDttm(Date creDttm) {
        this.creDttm = creDttm;
    }

}
