package com.gq.meter.object;
// default package
// Generated Feb 21, 2013 4:19:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * NSRGConnDevice generated by hbm2java
 */
public class NSRGConnDevice implements java.io.Serializable {

    private NSRGConnDeviceId id;

    public NSRGConnDevice() {
    }

    public NSRGConnDevice(NSRGConnDeviceId id) {
        this.id = id;
    }

    public NSRGConnDeviceId getId() {
        return this.id;
    }

    public void setId(NSRGConnDeviceId id) {
        this.id = id;
    }

}
