package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 3:55:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrinterConnDeviceId generated by hbm2java
 */
public class PrinterConnDeviceId implements java.io.Serializable {

    private int runId;
    private String assetId;
    private String ipAddr;

    public PrinterConnDeviceId() {
    }

    public PrinterConnDeviceId(int runId, String assetId, String ipAddr) {
        this.runId = runId;
        this.assetId = assetId;
        this.ipAddr = ipAddr;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public String getIpAddr() {
        return this.ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof PrinterConnDeviceId)) return false;
        PrinterConnDeviceId castOther = (PrinterConnDeviceId) other;

        return (this.getRunId() == castOther.getRunId())
                && ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
                        && castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())))
                && ((this.getIpAddr() == castOther.getIpAddr()) || (this.getIpAddr() != null
                        && castOther.getIpAddr() != null && this.getIpAddr().equals(castOther.getIpAddr())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRunId();
        result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
        result = 37 * result + (getIpAddr() == null ? 0 : this.getIpAddr().hashCode());
        return result;
    }

}
