package com.gq.meter.object;

// default package
// Generated Aug 1, 2013 4:22:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CompType generated by hbm2java
 */
public class CompType implements java.io.Serializable {

    private String typeId;
    private String descr;

    public CompType() {
    }

    public CompType(String typeId, String descr) {
        this.typeId = typeId;
        this.descr = descr;
    }

    public String getTypeId() {
        return this.typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
