package com.gq.meter.object;

// default package
// Generated Aug 1, 2013 4:22:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CompType generated by hbm2java
 */
public class CompType implements java.io.Serializable {

    private String type_id;
    private String descr;

    public CompType() {
    }

    public CompType(String type_id, String descr) {
        this.type_id = type_id;
        this.descr = descr;
    }

    public String getType_id() {
		return type_id;
	}

	public void setType_id(String type_id) {
		this.type_id = type_id;
	}

	public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
