package com.gq.meter.object;

// default package
// Generated Aug 1, 2013 2:27:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * DevCtlg generated by hbm2java
 */
public class DevCtlg implements java.io.Serializable {

    private String ctlgId = null;
    private String protocolId = null;
    private String descr = null;
    private short idleThreshold = 0;
    private short loadThreshold = 0;
    private double idleWatt = 0.0;
    private double loadWatt = 0.0;
    private Double enPerMinLoad = 0.0;
    private Double enPerMinIdle = 0.0;
    private Double servrCost = 0.0;
    private Integer noOfCore = 0;
    private Double cpu = 0.0;
    private Integer ram = 0;
    private Integer diskGb = 0;
    private Integer monthlyRent = 0;

    public DevCtlg() {
    }

    public DevCtlg(String ctlgId, String protocolId, String descr, short idleThreshold, short loadThreshold,
            double idleWatt, double loadWatt) {
        this.ctlgId = ctlgId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.idleThreshold = idleThreshold;
        this.loadThreshold = loadThreshold;
        this.idleWatt = idleWatt;
        this.loadWatt = loadWatt;
    }

    public DevCtlg(String ctlgId, String protocolId, String descr, short idleThreshold, short loadThreshold,
            double idleWatt, double loadWatt, Double enPerMinLoad, Double enPerMinIdle, Double servrCost,
            Integer noOfCore, Double cpu, Integer ram, Integer diskGb, Integer monthlyRent) {
        this.ctlgId = ctlgId;
        this.protocolId = protocolId;
        this.descr = descr;
        this.idleThreshold = idleThreshold;
        this.loadThreshold = loadThreshold;
        this.idleWatt = idleWatt;
        this.loadWatt = loadWatt;
        this.enPerMinLoad = enPerMinLoad;
        this.enPerMinIdle = enPerMinIdle;
        this.servrCost = servrCost;
        this.noOfCore = noOfCore;
        this.cpu = cpu;
        this.ram = ram;
        this.diskGb = diskGb;
        this.monthlyRent = monthlyRent;
    }

    public String getCtlgId() {
        return this.ctlgId;
    }

    public void setCtlgId(String ctlgId) {
        this.ctlgId = ctlgId;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
        System.out.println("Description:" + descr);
    }

    public short getIdleThreshold() {
        return this.idleThreshold;
    }

    public void setIdleThreshold(short idleThreshold) {
        this.idleThreshold = idleThreshold;
    }

    public short getLoadThreshold() {
        return this.loadThreshold;
    }

    public void setLoadThreshold(short loadThreshold) {
        this.loadThreshold = loadThreshold;
    }

    public double getIdleWatt() {
        return this.idleWatt;
    }

    public void setIdleWatt(double idleWatt) {
        this.idleWatt = idleWatt;
    }

    public double getLoadWatt() {
        return this.loadWatt;
    }

    public void setLoadWatt(double loadWatt) {
        this.loadWatt = loadWatt;
    }

    public Double getEnPerMinLoad() {
        return this.enPerMinLoad;
    }

    public void setEnPerMinLoad(Double enPerMinLoad) {

        if (enPerMinLoad != null) {
            this.enPerMinLoad = enPerMinLoad;
        }

    }

    public Double getEnPerMinIdle() {
        return this.enPerMinIdle;
    }

    public void setEnPerMinIdle(Double enPerMinIdle) {
        if (enPerMinIdle != null) {
            this.enPerMinIdle = enPerMinIdle;
        }
    }

    public Double getServrCost() {
        return this.servrCost;
    }

    public void setServrCost(Double servrCost) {
        if (servrCost != null) {
            this.servrCost = servrCost;
        }
    }

    public Integer getNoOfCore() {
        return this.noOfCore;
    }

    public void setNoOfCore(Integer noOfCore) {
        if (noOfCore != null) {
            this.noOfCore = noOfCore;
        }
    }

    public Double getCpu() {
        return this.cpu;
    }

    public void setCpu(Double cpu) {
        if (cpu != null) {
            this.cpu = cpu;
        }
    }

    public Integer getRam() {
        return this.ram;
    }

    public void setRam(Integer ram) {
        if (ram != null) {
            this.ram = ram;
        }
    }

    public Integer getDiskGb() {
        return this.diskGb;
    }

    public void setDiskGb(Integer diskGb) {
        if (diskGb != null) {
            this.diskGb = diskGb;
        }
    }

    public Integer getMonthlyRent() {
        return this.monthlyRent;
    }

    public void setMonthlyRent(Integer monthlyRent) {
        if (monthlyRent != null) {
            this.monthlyRent = monthlyRent;
        }
    }

}
