package com.gq.meter.xchange.object;
// default package
// Generated Dec 4, 2013 10:51:52 AM by Hibernate Tools 3.4.0.CR1

/**
 * EnterpriseGoalId generated by hbm2java
 */
public class EnterpriseGoalId implements java.io.Serializable {

	private String enterpriseId;
	private String goalId;

	public EnterpriseGoalId() {
	}

	public EnterpriseGoalId(String enterpriseId, String goalId) {
		this.enterpriseId = enterpriseId;
		this.goalId = goalId;
	}

	public String getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	public String getGoalId() {
		return this.goalId;
	}

	public void setGoalId(String goalId) {
		this.goalId = goalId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnterpriseGoalId))
			return false;
		EnterpriseGoalId castOther = (EnterpriseGoalId) other;

		return ((this.getEnterpriseId() == castOther.getEnterpriseId()) || (this
				.getEnterpriseId() != null
				&& castOther.getEnterpriseId() != null && this
				.getEnterpriseId().equals(castOther.getEnterpriseId())))
				&& ((this.getGoalId() == castOther.getGoalId()) || (this
						.getGoalId() != null && castOther.getGoalId() != null && this
						.getGoalId().equals(castOther.getGoalId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEnterpriseId() == null ? 0 : this.getEnterpriseId()
						.hashCode());
		result = 37 * result
				+ (getGoalId() == null ? 0 : this.getGoalId().hashCode());
		return result;
	}

}
