package com.gq.meter.xchange.object;
// default package
// Generated Dec 4, 2013 10:51:52 AM by Hibernate Tools 3.4.0.CR1

/**
 * EnterpriseGoal generated by hbm2java
 */
public class EnterpriseGoal implements java.io.Serializable {

	private EnterpriseGoalId id;

	public EnterpriseGoal() {
	}

	public EnterpriseGoal(EnterpriseGoalId id) {
		this.id = id;
	}

	public EnterpriseGoalId getId() {
		return this.id;
	}

	public void setId(EnterpriseGoalId id) {
		this.id = id;
	}

}
