package com.gq.meter.object;

// default package
// Generated Aug 1, 2013 4:22:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AssetImp generated by hbm2java
 */
public class AssetImp implements java.io.Serializable {

    private byte impLvl;
    private String descr;

    public AssetImp() {
    }

    public AssetImp(byte impLvl, String descr) {
        this.impLvl = impLvl;
        this.descr = descr;
    }

    public byte getImpLvl() {
        return this.impLvl;
    }

    public void setImpLvl(byte impLvl) {
        this.impLvl = impLvl;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }
}
