package com.gq.meter.object;

// Generated Feb 18, 2013 12:46:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * DeviceCatalog generated by hbm2java
 */
public class DeviceCatalog implements java.io.Serializable {

    private String ctlgId;
    private String descr;
    private short idlePctg;
    private short fullPctg;
    private double idleWatt;
    private double fullWatt;

    public DeviceCatalog() {
    }

    public DeviceCatalog(String ctlgId, String descr, short idlePctg, short fullPctg, double idleWatt, double fullWatt) {
        super();
        this.ctlgId = ctlgId;
        this.descr = descr;
        this.idlePctg = idlePctg;
        this.fullPctg = fullPctg;
        this.idleWatt = idleWatt;
        this.fullWatt = fullWatt;
    }

    public String getCtlgId() {
        return this.ctlgId;
    }

    public void setCtlgId(String ctlgId) {
        this.ctlgId = ctlgId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public short getIdlePctg() {
        return this.idlePctg;
    }

    public void setIdlePctg(short idlePctg) {
        this.idlePctg = idlePctg;
    }

    public short getFullPctg() {
        return this.fullPctg;
    }

    public void setFullPctg(short fullPctg) {
        this.fullPctg = fullPctg;
    }

    public double getIdleWatt() {
        return this.idleWatt;
    }

    public void setIdleWatt(double idleWatt) {
        this.idleWatt = idleWatt;
    }

    public double getFullWatt() {
        return this.fullWatt;
    }

    public void setFullWatt(double fullWatt) {
        this.fullWatt = fullWatt;
    }

}
