package com.gq.meter.object;

// default package
// Generated Sep 26, 2013 10:11:19 AM by Hibernate Tools 3.4.0.CR1

/**
 * GoalInput generated by hbm2java
 */
public class GoalInput implements java.io.Serializable {
    private String goalId;
    private short inputId;
    private String colHoldr;
    private String descr;
    private String dtvalue;

    public GoalInput() {
    }

    public GoalInput(String goalId, short inputId, String colHoldr, String descr, String dtvalue) {
        this.goalId = goalId;
        this.inputId = inputId;
        this.colHoldr = colHoldr;
        this.descr = descr;
        this.dtvalue = dtvalue;
    }

    public String getGoalId() {
        return goalId;
    }

    public void setGoalId(String goalId) {
        this.goalId = goalId;
    }

    public short getInputId() {
        return inputId;
    }

    public void setInputId(int i) {
        this.inputId = (short) i;
    }

    public String getColHoldr() {
        return this.colHoldr;
    }

    public void setColHoldr(String colHoldr) {
        this.colHoldr = colHoldr;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getDtvalue() {
        return this.dtvalue;
    }

    public void setDtvalue(String dtvalue) {
        this.dtvalue = dtvalue;
    }

}
