package com.gq.meter.object;

// default package
// Generated Apr 10, 2013 12:26:11 PM by Hibernate Tools 3.4.0.CR1

/**
 * SrvrAppType generated by hbm2java
 */
public class SrvrAppType implements java.io.Serializable {

    private String srvrAppId;
    private String descr;

    public SrvrAppType() {
    }

    public SrvrAppType(String srvrAppId, String descr) {
        this.srvrAppId = srvrAppId;
        this.descr = descr;
    }

    public String getSrvrAppId() {
        return this.srvrAppId;
    }

    public void setSrvrAppId(String srvrAppId) {
        this.srvrAppId = srvrAppId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
