package com.gq.meter.object;

// default package
// Generated Jul 10, 2013 2:52:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompSnpshtId generated by hbm2java
 */
public class CompSnpshtId implements java.io.Serializable {

    private int runId;
    private String assetId;

    public CompSnpshtId() {
    }

    public CompSnpshtId(int runId, String assetId) {
        this.runId = runId;
        this.assetId = assetId;
    }

    public int getRunId() {
        return this.runId;
    }

    public void setRunId(int runId) {
        this.runId = runId;
    }

    public String getAssetId() {
        return this.assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof CompSnpshtId)) return false;
        CompSnpshtId castOther = (CompSnpshtId) other;

        return (this.getRunId() == castOther.getRunId())
                && ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
                        && castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getRunId();
        result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
        return result;
    }

}
