package com.gq.meter.object;
// default package
// Generated Aug 1, 2013 3:46:57 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Protocol generated by hbm2java
 */
public class Protocol implements java.io.Serializable {

    private String protocolId;
    private String descr;
    private Set assets = new HashSet(0);

    public Protocol() {
    }

    public Protocol(String protocolId, String descr) {
        this.protocolId = protocolId;
        this.descr = descr;
    }

    public Protocol(String protocolId, String descr, Set assets) {
        this.protocolId = protocolId;
        this.descr = descr;
        this.assets = assets;
    }

    public String getProtocolId() {
        return this.protocolId;
    }

    public void setProtocolId(String protocolId) {
        this.protocolId = protocolId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public Set getAssets() {
        return this.assets;
    }

    public void setAssets(Set assets) {
        this.assets = assets;
    }

}
