package com.gq.meter.object;

// Generated Mar 1, 2013 12:58:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * SecurityQuestion generated by hbm2java
 */
public class SecurityQuestion implements java.io.Serializable {

    private short questionId;
    private String question;

    public SecurityQuestion() {
    }

    public SecurityQuestion(short questionId, String question) {
        this.questionId = questionId;
        this.question = question;
    }

    public short getQuestionId() {
        return this.questionId;
    }

    public void setQuestionId(short questionId) {
        this.questionId = questionId;
    }

    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

}
