package com.gq.meter.object;

// Generated Mar 1, 2013 12:56:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Enterprise generated by hbm2java
 */
public class Enterprise implements java.io.Serializable
{

	private String	enterpriseId;
	private char	blCd;
	private String	EName;
	private String	phone;
	private String	email;
	private Short	port;
	private String	userId;
	private String	UName;
	private String	passwd;
	private Short	secQtn1;
	private String	ans1;
	private Short	secQtn2;
	private String	ans2;
	private Date	creDttm;
	private Integer	noOfEmpl;
	private Integer	noOfAssets;
	private Integer	dcSqft;
	private String	comments;
	private char	storeFwd;
	private String	fwdUrl;
	private char	regCmplt;

	public Enterprise()
	{
	}

	public Enterprise(String enterpriseId, char blCd, String EName, String phone, String email, Short port, String userId,
			String UName, String passwd, Short secQtn1, String ans1, Short secQtn2, String ans2, Date creDttm, Integer noOfEmpl,
			Integer noOfAssets, Integer dcSqft, String comments, char storeFwd, String fwdUrl, char regCmplt)
	{
		this.enterpriseId = enterpriseId;
		this.blCd = blCd;
		this.EName = EName;
		this.phone = phone;
		this.email = email;
		this.port = port;
		this.userId = userId;
		this.UName = UName;
		this.passwd = passwd;
		this.secQtn1 = secQtn1;
		this.ans1 = ans1;
		this.secQtn2 = secQtn2;
		this.ans2 = ans2;
		this.creDttm = creDttm;
		this.noOfEmpl = noOfEmpl;
		this.noOfAssets = noOfAssets;
		this.dcSqft = dcSqft;
		this.comments = comments;
		this.storeFwd = storeFwd;
		this.fwdUrl = fwdUrl;
		this.regCmplt = regCmplt;
	}

	public String getEnterpriseId()
	{
		return this.enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId)
	{
		this.enterpriseId = enterpriseId;
	}

	public char getBlCd()
	{
		return this.blCd;
	}

	public void setBlCd(char blCd)
	{
		this.blCd = blCd;
	}

	public String getEName()
	{
		return this.EName;
	}

	public void setEName(String EName)
	{
		this.EName = EName;
	}

	public String getPhone()
	{
		return this.phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public Short getPort()
	{
		return this.port;
	}

	public void setPort(Short port)
	{
		this.port = port;
	}

	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getUName()
	{
		return this.UName;
	}

	public void setUName(String UName)
	{
		this.UName = UName;
	}

	public String getPasswd()
	{
		return this.passwd;
	}

	public void setPasswd(String passwd)
	{
		this.passwd = passwd;
	}

	public Short getSecQtn1()
	{
		return this.secQtn1;
	}

	public void setSecQtn1(Short secQtn1)
	{
		this.secQtn1 = secQtn1;
	}

	public String getAns1()
	{
		return this.ans1;
	}

	public void setAns1(String ans1)
	{
		this.ans1 = ans1;
	}

	public Short getSecQtn2()
	{
		return this.secQtn2;
	}

	public void setSecQtn2(Short secQtn2)
	{
		this.secQtn2 = secQtn2;
	}

	public String getAns2()
	{
		return this.ans2;
	}

	public void setAns2(String ans2)
	{
		this.ans2 = ans2;
	}

	public Date getCreDttm()
	{
		return this.creDttm;
	}

	public void setCreDttm(Date creDttm)
	{
		this.creDttm = creDttm;
	}

	public Integer getNoOfEmpl()
	{
		return this.noOfEmpl;
	}

	public void setNoOfEmpl(Integer noOfEmpl)
	{
		this.noOfEmpl = noOfEmpl;
	}

	public Integer getNoOfAssets()
	{
		return this.noOfAssets;
	}

	public void setNoOfAssets(Integer noOfAssets)
	{
		this.noOfAssets = noOfAssets;
	}

	public Integer getDcSqft()
	{
		return this.dcSqft;
	}

	public void setDcSqft(Integer dcSqft)
	{
		this.dcSqft = dcSqft;
	}

	public String getComments()
	{
		return comments;
	}

	public void setComments(String comments)
	{
		this.comments = comments;
	}

	public char getStoreFwd()
	{
		return this.storeFwd;
	}

	public void setStoreFwd(char storeFwd)
	{
		this.storeFwd = storeFwd;
	}

	public String getFwdUrl()
	{
		return this.fwdUrl;
	}

	public void setFwdUrl(String fwdUrl)
	{
		this.fwdUrl = fwdUrl;
	}

	public char getRegCmplt()
	{
		return regCmplt;
	}

	public void setRegCmplt(char regCmplt)
	{
		this.regCmplt = regCmplt;
	}
}
