package com.gq.meter.object;

// Generated May 2, 2013 12:59:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GateKeeper generated by hbm2java
 */
public class GateKeeper implements java.io.Serializable {

    private String enterpriseId;
    private Date expDttm;

    public GateKeeper() {
    }

    public GateKeeper(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public GateKeeper(String enterpriseId, Date expDttm) {
        this.enterpriseId = enterpriseId;
        this.expDttm = expDttm;
    }

    public String getEnterpriseId() {
        return this.enterpriseId;
    }

    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public Date getExpDttm() {
        return this.expDttm;
    }

    public void setExpDttm(Date expDttm) {
        this.expDttm = expDttm;
    }

}
