package com.gq.meter.object;

// Generated Feb 18, 2013 3:22:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * CompType generated by hbm2java
 */
public class CompType implements java.io.Serializable {

    private String typeId;
    private String descr;

    public CompType() {
    }

    public CompType(String typeId) {
        this.typeId = typeId;
    }

    public CompType(String typeId, String descr) {
        super();
        this.typeId = typeId;
        this.descr = descr;
    }

    public String getTypeId() {
        return this.typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

}
