package com.gq.meter.object;

// default package
// Generated Feb 21, 2013 3:55:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrinterConnDevice generated by hbm2java
 */
public class PrinterConnDevice implements java.io.Serializable {

    private PrinterConnDeviceId id;

    public PrinterConnDevice() {
    }

    public PrinterConnDevice(PrinterConnDeviceId id) {
        this.id = id;
    }

    public PrinterConnDeviceId getId() {
        return this.id;
    }

    public void setId(PrinterConnDeviceId id) {
        this.id = id;
    }

}
