package com.gq.meter.object;

// Generated Feb 18, 2013 12:49:24 PM by Hibernate Tools 3.4.0.CR1

/**
 * PrinterSnapshot generated by hbm2java
 */
public class PrinterSnapshot implements java.io.Serializable {

    private CPNId id;
    private String ipAddr;
    private Long totMem;
    private Long totDiskSpace;
    private Long usedMem;
    private Long usedDiskSpace;
    private Long upTime;
    private String toner_status;
    private Character outOfPaprInd;
    private Short prntsTknCnt;
    private int prntr_status;
    private int aux_status;
    private String mfgMdl;
    private String clrPrntr;
    private String extras;

    public PrinterSnapshot(CPNId id, String ipAddr, Long totMem, Long totDiskSpace, Long usedMem, Long usedDiskSpace,
            Long upTime, String toner_status, Character outOfPaprInd, Short prntsTknCnt, String mfgMdl,
            String clrPrntr, String extras, int prntr_status, int aux_status) {
        super();
        this.id = id;
        this.ipAddr = ipAddr;
        this.totMem = totMem;
        this.totDiskSpace = totDiskSpace;
        this.usedMem = usedMem;
        this.usedDiskSpace = usedDiskSpace;
        this.upTime = upTime;
        this.toner_status = toner_status;
        this.outOfPaprInd = outOfPaprInd;
        this.prntsTknCnt = prntsTknCnt;
        this.mfgMdl = mfgMdl;
        this.clrPrntr = clrPrntr;
        this.extras = extras;
        this.prntr_status = prntr_status;
        this.aux_status = aux_status;
    }

    /**
     * @return the prntr_status
     */
    public int getPrntr_status() {
        return prntr_status;
    }

    /**
     * @param prntr_status the prntr_status to set
     */
    public void setPrntr_status(int prntr_status) {
        this.prntr_status = prntr_status;
    }

    /**
     * @return the aux_status
     */
    public int getAux_status() {
        return aux_status;
    }

    /**
     * @param aux_status the aux_status to set
     */
    public void setAux_status(int aux_status) {
        this.aux_status = aux_status;
    }

    public CPNId getId() {
        return this.id;
    }

    public void setId(CPNId id) {
        this.id = id;
    }

    public String getIpAddr() {
        return this.ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    public Long getTotMem() {
        return this.totMem;
    }

    public void setTotMem(Long totMem) {
        this.totMem = totMem;
    }

    public Long getTotDiskSpace() {
        return this.totDiskSpace;
    }

    public void setTotDiskSpace(Long totDiskSpace) {
        this.totDiskSpace = totDiskSpace;
    }

    public Long getUsedMem() {
        return this.usedMem;
    }

    public void setUsedMem(Long usedMem) {
        this.usedMem = usedMem;
    }

    public Long getUsedDiskSpace() {
        return this.usedDiskSpace;
    }

    public void setUsedDiskSpace(Long usedDiskSpace) {
        this.usedDiskSpace = usedDiskSpace;
    }

    public Long getUpTime() {
        return this.upTime;
    }

    public void setUpTime(Long upTime) {
        this.upTime = upTime;
    }

    /**
     * @return the toner_status
     */
    public String getToner_status() {
        return toner_status;
    }

    /**
     * @param toner_status the toner_status to set
     */
    public void setToner_status(String toner_status) {
        this.toner_status = toner_status;
    }

    public Character getOutOfPaprInd() {
        return this.outOfPaprInd;
    }

    public void setOutOfPaprInd(Character outOfPaprInd) {
        this.outOfPaprInd = outOfPaprInd;
    }

    public Short getPrntsTknCnt() {
        return this.prntsTknCnt;
    }

    public void setPrntsTknCnt(Short prntsTknCnt) {
        this.prntsTknCnt = prntsTknCnt;
    }

    public String getMfgMdl() {
        return this.mfgMdl;
    }

    public void setMfgMdl(String mfgMdl) {
        this.mfgMdl = mfgMdl;
    }

    public String getClrPrntr() {
        return this.clrPrntr;
    }

    public void setClrPrntr(String clrPrntr) {
        this.clrPrntr = clrPrntr;
    }

    public String getExtras() {
        return this.extras;
    }

    public void setExtras(String extras) {
        this.extras = extras;
    }

}
