package com.gq.meter.object;
// default package
// Generated Dec 30, 2013 4:14:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * SpeedTestSnpsht generated by hbm2java
 */
public class SpeedTestSnpsht implements java.io.Serializable {

	private SpeedTestSnpshtId id;
	private Double upldSpdMbs;
	private Double dwnldSpdMbs;

	public SpeedTestSnpsht() {
	}

	public SpeedTestSnpsht(SpeedTestSnpshtId id) {
		this.id = id;
	}

	public SpeedTestSnpsht(SpeedTestSnpshtId id, Double upldSpdMbs,
			Double dwnldSpdMbs) {
		this.id = id;
		this.upldSpdMbs = upldSpdMbs;
		this.dwnldSpdMbs = dwnldSpdMbs;
	}

	public SpeedTestSnpshtId getId() {
		return this.id;
	}

	public void setId(SpeedTestSnpshtId id) {
		this.id = id;
	}

	public Double getUpldSpdMbs() {
		return this.upldSpdMbs;
	}

	public void setUpldSpdMbs(Double upldSpdMbs) {
		this.upldSpdMbs = upldSpdMbs;
	}

	public Double getDwnldSpdMbs() {
		return this.dwnldSpdMbs;
	}

	public void setDwnldSpdMbs(Double dwnldSpdMbs) {
		this.dwnldSpdMbs = dwnldSpdMbs;
	}

}
