package com.gq.meter.object;

// default package
// Generated Jul 10, 2013 1:41:53 PM by Hibernate Tools 3.4.0.CR1

/**
 * SysProfile generated by hbm2java
 */
public class SysProfile implements java.io.Serializable {

    private String keyy;
    private String value;

    public SysProfile() {
    }

    public SysProfile(String keyy) {
        this.keyy = keyy;
    }

    public SysProfile(String keyy, String value) {
        this.keyy = keyy;
        this.value = value;
    }

    public String getKeyy() {
        return this.keyy;
    }

    public void setKeyy(String keyy) {
        this.keyy = keyy;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
