package com.gq.meter.xchange.object;

// Generated Mar 1, 2013 12:56:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ClientData generated by hbm2java
 */
public class ClientData implements java.io.Serializable {

    private Integer runId;
    private String data;
    private Date fwdDttm;

    public ClientData() {
    }

    public ClientData(String data, Date fwdDttm) {
        this.data = data;
        this.fwdDttm = fwdDttm;
    }

    public Integer getRunId() {
        return this.runId;
    }

    public void setRunId(Integer runId) {
        this.runId = runId;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Date getFwdDttm() {
        return this.fwdDttm;
    }

    public void setFwdDttm(Date fwdDttm) {
        this.fwdDttm = fwdDttm;
    }

}
