package com.gq.meter.xchange.object;

// Generated Mar 1, 2013 12:57:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GateKeeper generated by hbm2java
 */
public class GateKeeper implements java.io.Serializable {

    private String meterId;
    private Date expDttm;
    private Integer scnAlwd;
    private Integer scnRmng;
    private char chkCndtn;

    public GateKeeper() {
    }

    public GateKeeper(String meterId, char chkCndtn) {
        this.meterId = meterId;
        this.chkCndtn = chkCndtn;
    }

    public GateKeeper(String meterId, Date expDttm, Long totScnAlwd, Integer scnRmng, char chkCndtn) {
        this.meterId = meterId;
        this.expDttm = expDttm;
        this.scnAlwd = scnAlwd;
        this.scnRmng = scnRmng;
        this.chkCndtn = chkCndtn;
    }

    public String getMeterId() {
        return this.meterId;
    }

    public void setMeterId(String meterId) {
        this.meterId = meterId;
    }

    public Date getExpDttm() {
        return this.expDttm;
    }

    public void setExpDttm(Date expDttm) {
        this.expDttm = expDttm;
    }

    public Integer getScnAlwd() {
        return this.scnAlwd;
    }

    public void setScnAlwd(Integer scnAlwd) {
        this.scnAlwd = scnAlwd;
    }

    public Integer getScnRmng() {
        return this.scnRmng;
    }

    public void setScnRmng(Integer scnRmng) {
        this.scnRmng = scnRmng;
    }

    public char getChkCndtn() {
        return this.chkCndtn;
    }

    public void setChkCndtn(char chkCndtn) {
        this.chkCndtn = chkCndtn;
    }

}
