package com.gq.meter.xchange.object;

// default package
// Generated Jul 26, 2013 10:19:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * GoalSnpsht generated by hbm2java
 */
public class GoalSnpsht implements java.io.Serializable {

    private int snpshtId;
    private Goal goal;
    private String enterpriseId;
    private Date startDate;
    private Date endDate;
    private String notes;
    private Integer costBenefit;
    private String preResult;
    private String postResult;

    public GoalSnpsht() {
    }

    public GoalSnpsht(int snpshtId, Goal goal, Date startDate) {
        this.snpshtId = snpshtId;
        this.goal = goal;
        this.startDate = startDate;
    }

    public GoalSnpsht(int snpshtId, Goal goal, String enterpriseId, Date startDate, Date endDate, String notes,
            Integer costBenefit, String preResult, String postResult) {
        this.snpshtId = snpshtId;
        this.goal = goal;
        this.enterpriseId = enterpriseId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.notes = notes;
        this.costBenefit = costBenefit;
        this.preResult = preResult;
        this.postResult = postResult;
    }

    public int getSnpshtId() {
        return this.snpshtId;
    }

    public void setSnpshtId(int snpshtId) {
        this.snpshtId = snpshtId;
    }

    public Goal getGoal() {
        return this.goal;
    }

    public void setGoal(Goal goal) {
        this.goal = goal;
    }

    public String getEnterpriseId() {
        return enterpriseId;
    }

    public void setEnterpriseId(String enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getCostBenefit() {
        return this.costBenefit;
    }

    public void setCostBenefit(Integer costBenefit) {
        this.costBenefit = costBenefit;
    }

    public String getPreResult() {
        return this.preResult;
    }

    public void setPreResult(String preResult) {
        this.preResult = preResult;
    }

    public String getPostResult() {
        return this.postResult;
    }

    public void setPostResult(String postResult) {
        this.postResult = postResult;
    }

}
