package com.gq.meter.xchange.object;

// default package
// Generated Sep 13, 2013 10:43:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * GoalInput generated by hbm2java
 */
public class GoalInput implements java.io.Serializable {

    private GoalInputId id;
    private String colHoldr;
    private String descr;
    private String dtvalue;

    public GoalInput() {
    }

    public GoalInput(GoalInputId id, String colHoldr, String descr, String dtvalue) {
        this.id = id;
        this.colHoldr = colHoldr;
        this.descr = descr;
        this.dtvalue = dtvalue;
    }

    public GoalInputId getId() {
        return this.id;
    }

    public void setId(GoalInputId id) {
        this.id = id;
    }

    public String getColHoldr() {
        return this.colHoldr;
    }

    public void setColHoldr(String colHoldr) {
        this.colHoldr = colHoldr;
    }

    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    public String getDtvalue() {
        return this.dtvalue;
    }

    public void setDtvalue(String dtvalue) {
        this.dtvalue = dtvalue;
    }

}
